name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build -- --configuration production --base-href "https://ljclaeyssen.github.io/memory-ocre-ambre/"

      - name: Move browser files to root
        run: |
          mv dist/ocre-ambre/browser/* dist/ocre-ambre/
          rm -rf dist/ocre-ambre/browser

      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Deploy to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/ocre-ambre/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
